name: Run Doc Detective Tests

on:
  push:
    branches:
      - gh-pages

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Doc Detective repository
      uses: actions/checkout@v2
      with:
        repository: 'doc-detective/doc-detective'
        path: 'doc-detective'  # Check out the doc-detective repo into a 'doc-detective' directorya

    - name: Checkout nikomancy/doc-detective-ci-cd repository
      uses: actions/checkout@v2
      with:
        repository: 'nikomancy/doc-detective-ci-cd'
        ref: 'gh-pages'  # Specify the branch to checkout
        path: 'doc-detective-ci-cd'  # Check out the repository into a 'doc-detective-ci-cd' directory

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Chrome Browser
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -f install -y

    - name: Set Puppeteer Environment Variables
      run: |
        echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV
        echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome" >> $GITHUB_ENV

    - name: Install Doc Detective dependencies
      run: |
        cd doc-detective
        npm ci --verbose

    - name: Run Doc Detective tests
      run: |
        cd doc-detective
        npm run runTests -- --input ../doc-detective-ci-cd/_posts/
